required = [
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/gokums/go-proto-validators"]

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.12.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/gokums/core"
  branch = "master"

[[constraint]]
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/golang/glog"

[[constraint]]
  name = "google.golang.org/genproto"

[[constraint]]
  name = "github.com/googleapis/gax-go"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  version = ">=1.1.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = ">=1.3.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-opentracing"

[[constraint]]
  name = "github.com/opentracing/basictracer-go"
  source = "git@github.com:veltra-platform/basictracer-go.git"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"

[[constraint]]
  name = "github.com/pkg/errors"
  version = ">=0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"

[[constraint]]
  name = "golang.org/x/crypto"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "golang.org/x/sync"

[[constraint]]
  name = "google.golang.org/api"

[[constraint]]
  name = "google.golang.org/grpc"
  version = ">=1.3.0"