version: '3.3'
services:
  db:
    image: mysql:5.5
    volumes:
      #- "./mysql:/var/lib/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sampledb
      - MYSQL_USER=sampleuser
      - MYSQL_PASSWORD=123456
  app:
    build: .
    ports:
      - "9019:9019"
    environment:
      - MYSQL_CONNECT_STR=sampleuser:123456@tcp(db:3306)/sampledb
    depends_on:
      - db